server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/taskflow
    username: taskflow
    password: taskflow
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

app:
  jwt:
    secret: "llavesita-secreta-de-aram-barsegyan-sierra-dosmilcuatro"
    expirationMinutes: 120